DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS logger;
DROP TABLE IF EXISTS proyect;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS proyectStatus;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    firstname TEXT NOT NULL,
    secondname TEXT NOT NULL,
    password TEXT NOT NULL,
    roleId INTEGER,
    proyId INTEGER,
    auth INTEGER,

    FOREIGN KEY (roleId) REFERENCES roles(id),
    FOREIGN KEY (proyId) REFERENCES proyect(id)
);

CREATE TABLE proyect (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    description TEXT UNIQUE NOT NULL,
    start DATE NOT NULL,
    end DATE NOT NULL,
    statusId INTEGER,

    FOREIGN KEY (statusId) REFERENCES proyectStatus(id)
);

CREATE TABLE logger (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event TEXT NOT NULL,
    date TEXT NOT NULL,
    user TEXT NOT NULL
);

CREATE TABLE roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE proyectStatus (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);
