DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS logger;
DROP TABLE IF EXISTS systems;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS proyect;
DROP TABLE IF EXISTS user_proyect;
DROP TABLE IF EXISTS roles;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    firstname TEXT NOT NULL,
    secondname TEXT NOT NULL,
    password TEXT NOT NULL,
    roleId INTEGER,
    proyId INTEGER,
    auth INTEGER,

    FOREIGN KEY (proyId) REFERENCES proyect(id),
    FOREIGN KEY (roleId) REFERENCES roles(id) 
);

CREATE TABLE proyect (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    description TEXT UNIQUE NOT NULL,
    start DATE NOT NULL,
    end DATE NOT NULL,
    status INTEGER
);

CREATE TABLE logger (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event TEXT NOT NULL,
    date TEXT NOT NULL,
    user TEXT NOT NULL

    FOREIGN KEY (user) REFERENCES user(username)
);

CREATE TABLE roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
);
